name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # Set up JDK
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Change wrapper permissions
      run: chmod +x ./AndroidStudioProject/gradlew
    
    # Build the project
    - name: Build with Gradle
      run: ./AndroidStudioProject/gradlew build
